/**
 * FlashAttention V2 — Host-side operator registration
 * ======================================================
 * CANN 8.5.0 custom op for Ascend NPU deployment.
 *
 * Inputs:
 *   query  : [B, Hq, Sq, D]  half
 *   key    : [B, Hkv, Sk, D] half
 *   value  : [B, Hkv, Sk, D] half
 * Outputs:
 *   output : [B, Hq, Sq, D]  half
 *
 * Tiling data (FlashAttentionTilingData + two TCubeTiling structs)
 * is generated by gen_tiling.py and passed via tiling GM buffer.
 */

#include <cstdint>
#include "register/register.h"
#include "graph/operator_reg.h"
#include "../flash_attention_tiling.h"

using domi::OpReceiver;
using domi::OpRegistrationData;

// ---------------------------------------------------------------------------
// Shape inference: query → output
// ---------------------------------------------------------------------------
IMPLEMT_INFERFUNC(FlashAttentionV2, FlashAttentionInfer) {
    auto qDesc = op.GetInputDesc(0);
    op.UpdateOutputDesc(0, qDesc);
    return GRAPH_SUCCESS;
}
INFER_FUNC_REG(FlashAttentionV2, FlashAttentionInfer);

// ---------------------------------------------------------------------------
// Common infer function
// ---------------------------------------------------------------------------
IMPLEMT_COMMON_INFERFUNC(FlashAttentionV2InferShape) {
    auto qDesc = op.GetInputDesc(0);
    op.UpdateOutputDesc(0, qDesc);
    return GRAPH_SUCCESS;
}
COMMON_INFER_FUNC_REG(FlashAttentionV2, FlashAttentionV2InferShape);

// ---------------------------------------------------------------------------
// Operator registration
// ---------------------------------------------------------------------------
REGISTER_CUSTOM_OP(FlashAttentionV2)
    .FrameworkType(domi::CAFFE)
    .OriginOpType("FlashAttentionV2");
