/**
 * FlashAttention operator — Host side
 * CANN 9.0.0 custom op for Ascend NPU.
 *
 * Inputs:
 *   query  : [B, Hq, Sq, D]  half
 *   key    : [B, Hkv, Sk, D] half
 *   value  : [B, Hkv, Sk, D] half
 * Outputs:
 *   output : [B, Hq, Sq, D]  half
 *
 * Tiling data (FlashAttentionTilingData + two TCubeTiling structs)
 * is generated by the application and passed via tiling GM buffer.
 */

#include <cstdint>
#include "register/register.h"
#include "graph/operator_reg.h"
#include "../op_kernel/flash_attention_tiling.h"

using domi::OpReceiver;
using domi::OpRegistrationData;

// ---------------------------------------------------------------------------
// Shape inference: query → output
// ---------------------------------------------------------------------------
IMPLEMT_INFERFUNC(KlmsFlashAttention, FlashAttentionInfer) {
    auto qDesc = op.GetInputDesc(0);
    op.UpdateOutputDesc(0, qDesc);
    return GRAPH_SUCCESS;
}
INFER_FUNC_REG(KlmsFlashAttention, FlashAttentionInfer);

// ---------------------------------------------------------------------------
// Common infer function
// ---------------------------------------------------------------------------
IMPLEMT_COMMON_INFERFUNC(KlmsFlashAttentionInferShape) {
    auto qDesc = op.GetInputDesc(0);
    op.UpdateOutputDesc(0, qDesc);
    return GRAPH_SUCCESS;
}
COMMON_INFER_FUNC_REG(KlmsFlashAttention, KlmsFlashAttentionInferShape);

// ---------------------------------------------------------------------------
// Operator registration
// ---------------------------------------------------------------------------
REGISTER_CUSTOM_OP(KlmsFlashAttention)
    .FrameworkType(domi::CAFFE)
    .OriginOpType("KlmsFlashAttention");
